# Markdown renderer configuration
[goldmark.renderer]
unsafe = false

[tableOfContents]
endLevel = 4
ordered = true
startLevel = 2

[highlight]
noClasses = false
codeFences = true
guessSyntax = true
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
tabWidth = 4


## TODO: Socials aren't showing? links page?
[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/jpomfret"

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/jpomfret"

[social.params]
icon = "brand-twitter"