## github
[[social]]
identifier = "github"
    name = "GitHub"
    url = "https://github.com/jpomfret"

[social.params]
icon = "brand-github"

## bluesky
[[social]]
identifier = "bluesky"
    name = "bluesky"
    url = "https://bsky.app/profile/jpomfret.bsky.social"

[social.params]
icon = "bluesky"

# insta
[[social]]
identifier = "instagram"
    name = "instagram"
    url = "https://www.instagram.com/jpomfret/"

[social.params]
icon = "instagram"

# sessionize
[[social]]
identifier = "sessionize"
    name = "sessionize"
    url = "https://sessionize.com/jpomfret/"

[social.params]
icon = "sesh"

# linkedin
[[social]]
identifier = "linkedin"
    name = "linkedin"
    url = "https://www.linkedin.com/in/jpomfret/"

[social.params]
icon = "linkedin"
